version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    environment:
      - EMQX_NODE_NAME="telemetry-broker"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - rats-net
    depends_on:
      - timescaledb
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Rocketry2526
      - PGDATA=/pgdata
    volumes:
      - timescaledb_data:/pgdata
    networks:
      - rats-net
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rats-net
    depends_on: timescaledb
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock # Gives Portainer control of Docker
    networks:
      - rats-net
    restart: unless-stopped
networks:
  rats-net:
    driver: bridge
volumes:
  emqx_data:
  emqx_log:
  timescaledb_data:
  grafana_data:
  portainer_data:
