{
 "title": "FillOps",
 "time": { "from": "2026-01-15T17:10:27.576Z", "to": "2026-01-15T17:10:31.146Z" },
 "panels": [
  {
   "title": "Fill Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fill Station Cameras",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<div style=\"display: flex; flex-direction: row; gap: 10px; width: 100%; height: 100%; align-items: center; justify-content: center; overflow: hidden;\">\n    \n    <iframe style=\"flex: 1 1 0; min-width: 0; aspect-ratio: 4 / 3; border: none;\" \n       src=\"http://192.168.8.193:1984/stream.html?src=fillcam0\" \n       allowfullscreen allow=\"autoplay; fullscreen\">\n    </iframe>\n\n    <iframe style=\"flex: 1 1 0; min-width: 0; aspect-ratio: 4 / 3; border: none;\" \n       src=\"http://192.168.8.193:1984/stream.html?src=fillcam1\" \n       allowfullscreen allow=\"autoplay; fullscreen\">\n    </iframe>\n\n    <iframe style=\"flex: 1 1 0; min-width: 0; aspect-ratio: 4 / 3; border: none;\" \n       src=\"http://192.168.8.193:1984/stream.html?src=fillcam2\" \n       allowfullscreen allow=\"autoplay; fullscreen\">\n    </iframe>\n\n</div>"
     }
    },
    {
     "title": "Fill System Pressures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  pt_1_pressure AS \"PT1\",\n  pt_2_pressure AS \"PT2\",\n  pt3 AS \"PT3\",\n  pt4 AS \"PT4\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 0\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Load Cell",
     "type": "gauge",
     "gridPos": { "h": 14, "w": 8, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "masslb" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  load_cell AS \"Propellant Mass\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND\n  unit_id = 0\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Pad Safety",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 20, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  qd_state AS \"QD Step\",\n  flight_mode AS \"Flight Mode\",\n  ignition AS \"Ignition Command\"\nFROM telemetry_data\nWHERE\n  unit_id = 0\nORDER BY time DESC\nLIMIT 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  pt_1_pressure AS \"PT1\",\n  pt_2_pressure AS \"PT2\",\n  pt3 AS \"PT3\",\n  pt4 AS \"PT4\"\nFROM telemetry_data\nWHERE unit_id = 0\nORDER BY time DESC\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "Valve Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  sv_1_open AS \"SV1\",\n  sv_2_open AS \"SV2\",\n  ball_valve_open AS \"Ball Valve\",\n  mav_open AS \"MAV\"\nFROM telemetry_data\nWHERE\n  unit_id = 0\nORDER BY time DESC\nLIMIT 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Pre-Flight Avionics Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "AV Bay Temps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  temp AS \"Altimeter Temp\",\n  rtd AS \"ADC RTD Temp\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id IN (0, 1)\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "GPS Health",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "Satellites in View" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  num_satellites AS \"Satellites\"\nFROM telemetry_data\nWHERE unit_id IN (0, 1)\nORDER BY time DESC\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Altimeter Health",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  altitude AS \"Altitude (m)\",\n  pressure AS \"Pressure (Pa)\",\n  temp AS \"Temp (°C)\"\nFROM telemetry_data\nWHERE unit_id IN (0, 1)\nORDER BY time DESC\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "IMU Health",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "accMS2" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  accel_z AS \"Z-Axis Accel (m/s²)\"\nFROM telemetry_data\nWHERE unit_id IN (0, 1)\nORDER BY time DESC\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Time Since Last Radio Packet",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - time)) AS \"Seconds Since Last Rx\"\nFROM telemetry_data\nWHERE unit_id = 1\nORDER BY time DESC\nLIMIT 1;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Flight Dynamics and Tracking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "LV Flight Path",
     "type": "geomap",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  latitude,\n  longitude\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Altitude",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  altitude AS \"Altitude\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Acceleration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "accMS2" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  accel_x AS \"X-Axis\",\n  accel_y AS \"Y-Axis\",\n  accel_z AS \"Z-Axis\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Rotational Velocity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "rotdegs" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  gyro_x AS \"Roll (X)\",\n  gyro_y AS \"Pitch (Y)\",\n  gyro_z AS \"Yaw (Z)\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Flight Mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  flight_mode AS \"Flight Mode\"\nFROM telemetry_data\nWHERE\n  unit_id = 1\nORDER BY time DESC\nLIMIT 1;"
      }
     ]
    },
    {
     "title": "LV Coordinates",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  latitude::numeric(10,5) || '°, ' || longitude::numeric(10,5) || '°' AS \"Coordinates\"\nFROM telemetry_data\nWHERE \n  unit_id = 1 \n  AND latitude != 0 \n  AND longitude != 0\nORDER BY time DESC\nLIMIT 1;\n"
      }
     ]
    },
    {
     "title": "Apogee",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  altitude AS \"Apogee\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1;\n"
      }
     ]
    },
    {
     "title": "Max Ascent Velocity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Mach" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Altitude",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  altitude AS \"Altitude\"\nFROM telemetry_data\nWHERE\n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Acceleration",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "accMS2" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  accel_x AS \"X-Axis\",\n  accel_y AS \"Y-Axis\",\n  accel_z AS \"Z-Axis\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Rotational Velocity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 14, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "rotdegs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  time AS \"time\",\n  gyro_x AS \"Roll (X)\",\n  gyro_y AS \"Pitch (Y)\",\n  gyro_z AS \"Yaw (Z)\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Horizontal Drift Velocity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Vertical Velocity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "WITH raw_data AS (\n  SELECT\n    time,\n    \n    -- Calculate velocities using the hardware timestamp, immune to network jitter\n    (altitude - lag(altitude) OVER (ORDER BY time)) / \n    NULLIF(\"timestamp\" - lag(\"timestamp\") OVER (ORDER BY time), 0) AS raw_vel_z,\n    \n    ((longitude - lag(longitude) OVER (ORDER BY time)) * (111139.0 * cos(radians(latitude)))) / \n    NULLIF(\"timestamp\" - lag(\"timestamp\") OVER (ORDER BY time), 0) AS raw_vel_x,\n    \n    ((latitude - lag(latitude) OVER (ORDER BY time)) * 111139.0) / \n    NULLIF(\"timestamp\" - lag(\"timestamp\") OVER (ORDER BY time), 0) AS raw_vel_y\n    \n  FROM telemetry_data\n  WHERE\n    $__timeFilter(time) AND \n    unit_id = 1 AND\n    latitude IS NOT NULL AND \n    longitude IS NOT NULL AND\n    latitude != 0 AND \n    longitude != 0\n),\nsmoothed AS (\n  SELECT\n    time,\n    ROW_NUMBER() OVER (ORDER BY time) AS pkt_num,\n    AVG(raw_vel_z) OVER (ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS vel_z,\n    AVG(raw_vel_x) OVER (ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS vel_x,\n    AVG(raw_vel_y) OVER (ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS vel_y\n  FROM raw_data\n)\nSELECT\n  time AS \"time\",\n  -- Mask the first 10 un-smoothed edge packets to stabilize the graph's Y-axis\n  CASE WHEN pkt_num > 10 THEN vel_z ELSE NULL END AS \"Vertical Velocity\",\n  CASE WHEN pkt_num > 10 THEN vel_z / 343.0 ELSE NULL END AS \"Mach\",\n  CASE WHEN pkt_num > 10 THEN vel_x ELSE NULL END AS \"Drift X\",\n  CASE WHEN pkt_num > 10 THEN vel_y ELSE NULL END AS \"Drift Y\",\n  CASE \n    WHEN pkt_num <= 10 THEN NULL\n    WHEN vel_x = 0 AND vel_y = 0 THEN 0 \n    ELSE MOD(CAST(atan2d(vel_x, vel_y) + 360 AS NUMERIC), 360) \n  END AS \"Heading\"\nFROM smoothed\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Vertical Velocity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 7, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Max Deployment Shock",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 14, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "accG" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "dataset": "postgres",
       "rawSql": "SELECT\n  ABS(accel_z) / 9.81 AS \"Max Peak Shock\"\nFROM telemetry_data\nWHERE\n  $__timeFilter(time) AND \n  unit_id = 1;\n"
      }
     ]
    },
    {
     "title": "Drift Heading",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    }
   ]
  },
  {
   "title": "Raw Telemetry (Debug/Diagnostic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Time Since Last Fill Station Packet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - time)) AS \"Seconds Since Last Rx\"\nFROM telemetry_data\nWHERE unit_id = 0\nORDER BY time DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Time Since Last Radio Packet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  EXTRACT(EPOCH FROM (NOW() - time)) AS \"Seconds Since Last Rx\"\nFROM telemetry_data\nWHERE unit_id = 1\nORDER BY time DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Raw Telemetry Table",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT *\nFROM telemetry_data\nWHERE unit_id IN (0,1)\nORDER BY time DESC\nLIMIT 20;\n"
    }
   ]
  }
 ]
}